### ISSUE TITLE
Connectioned timed out for gemini://gus.guru/

### ISSUE THREAD

**Issue by HammyHavoc** [kr1sp1n/awesome-gemini#117]
Is it dead?

**Comment by kr1sp1n** [comment]
@HammyHavoc I am not the maintainer of gus.guru or anything similar. This repo is just a list of gemini-related things. Maybe you could find out who is responsible for gus.guru and write an email to that person.

**Comment by HammyHavoc** [comment]
I am aware of this. My point is that a list that links to dead resources
isn't a particularly useful list. Perhaps we need a 'Down' or 'Dead'
section or just remove it completely?

**Comment by kr1sp1n** [comment]
Ah, now I see 😉 Sorry that I misunderstood your comment. Yes, we could just delete it from the list or ask the maintainer, if it is dead for sure.
