### ISSUE TITLE
bollux (bash) client website/repo moved

### ISSUE THREAD

**Issue by kwadroke** [kr1sp1n/awesome-gemini#120]
Moved from https://sr.ht/~acdw/bollux/ to https://tildegit.org/acdw/bollux

See the top of https://sr.ht/~acdw/bollux/ for more info

**Comment by kr1sp1n** [comment]
@kwadroke Please open a PR and add it to the README.md.

**Comment by kwadroke** [comment]
I will not be opening a PR at this time.
