### ISSUE TITLE
Add the following games and services:

### ISSUE THREAD

**Issue by stacksmith** [kr1sp1n/awesome-gemini#161]
Weather, using your IP address for location
gemini://tilde.cafe/~stack/weather
  or a specific location, for instance:
gemini://tilde.cafe/~stack/weather?nyc

Spellbinding game -- make words with specified letters
gemini://tilde.cafe/~spellbinding/game/cgi?

A wordle-like game
gemini://tilde.cafe/~spellbinding/wordo/cgi?

A public wall - leave a message
gemini://tilde.cafe/~spellbinding/wall/cgi

**Comment by kr1sp1n** [comment]
@stacksmith Please be so kind and open a Pull Request because I do not have the time to transform all the Github Issues to Pull Requests. Thanks!
