### ISSUE TITLE
We might wish to clarify the Galacteek entry

### ISSUE THREAD

**Issue by feoh** [kr1sp1n/awesome-gemini#168]
[Galacteek](https://github.com/pinnaculum/galacteek) does in fact support browsing the Gemini protocol, but it also installs an IPFS daemon on the user's machine and seems mostly oriented towards being a web3 / cryptocurrency / 'dapp' platform.

I'm not in any way suggesting ill will on the part of the submitter, but for those of us who would prefer to avoid that space it might be helpful to signpost what this is.

I'll submit a PR if folks are amenable.

**Comment by kr1sp1n** [comment]
@feoh Please be so kind and open a Pull Request because I do not have the time to transform all the Github Issues to Pull Requests. Thanks!
