### ISSUE TITLE
List that Amfora is in maintenance mode

### ISSUE THREAD

**Issue by Solomon1732** [kr1sp1n/awesome-gemini#169]
Amfora has been in maintenance mode since August. Is it possible to list it as such, such as through a comment or side note?

> Amfora is in maintenance mode. When possible, I’ll make/merge bug fixes, and maybe slowly merge feature PRs by others. See my [blog post](https://www.makeworld.space/2023/08/bye_gemini.html) for details.

Its repo: https://github.com/makew0rld/amfora
Blog post in question: https://www.makeworld.space/2023/08/bye_gemini.html

**Comment by kr1sp1n** [comment]
@Solomon1732 Please be so kind and open a Pull Request because I do not have the time to transform all the Github Issues to Pull Requests. Thanks!

**Comment by Solomon1732** [comment]
@kr1sp1n How should I handle it in the PR? Should I remove it from your Readme? Or should I merely add it's in maintenance mode?

**Comment by weakish** [comment]
> Should I remove it from your Readme? Or should I merely add it's in maintenance mode?

IMHO merely adding a note that it's in maintenance mode is better than removing it. Although it is not actively developed, it is still maintained so others can still use it.
