### ISSUE TITLE
add dioscuri

### ISSUE THREAD

**Issue by weakish** [kr1sp1n/awesome-gemini#175]
[dioscuri](https://github.com/wooorm/dioscuri) is a gemtext (`text/gemini`) parser with support for streaming, ASTs, and CSTs:

* buffering and streaming interfaces that compile to HTML
* interfaces to create [unist](https://github.com/syntax-tree/unist) compliant abstract syntax trees and serialize those back to gemtext
* interfaces to transform to and from [mdast](https://github.com/syntax-tree/mdast) (markdown ast)
* parts that could be used to generate CSTs

**Comment by kr1sp1n** [comment]
@weakish Please be so kind and open a Pull Request because I do not have the time to transform all the Github Issues to Pull Requests. Thanks!
