### ISSUE TITLE
Add astroget

### ISSUE THREAD

**Issue by zzo38** [kr1sp1n/awesome-gemini#179]
Add [astroget](https://github.com/zzo38/scorpion/blob/trunk/astroget.c), which is a command-line implementation of both download and upload, and implements schemes: `data:`, `file:`, `gemini:`, `gopher:`, `scorpion:`, `scorpions:`, `spartan:`. (It is not complete yet, but it is usable. More protocols and/or other features may be added later.)

**Comment by zzo38** [comment]
We should determine exactly what description should be best, and what section to use. Possibly "Terminal" (which seems to be where most of that kind of stuff is), although gemget is in the "Programming" section (why is that?). Actually, I think that a separate section for command-line programs (that are not meant to be interactive) would be better, probably.

Also, note that the repository I linked to has other files too, some of which are used by astroget, but they are otherwise not a part of astroget and are a separate project (which astroget is a part of, though, which is why it is there).

**Comment by weakish** [comment]
> although gemget is in the "Programming" section (why is that?)

This is strange since gemget is not a library but a command line utility.
I moved it to the Tools section and also add astroget there in #182
Technically both gem get and astroget are terminal clients but right now most items under the Clients/Terminal section are interactive clients (browsers).
