### ISSUE TITLE
flounder.online

### ISSUE THREAD

**Issue by alexwennerberg** [kr1sp1n/awesome-gemini#21]
Hey -- you might be interested in https://flounder.online/ & gemini://flounder.online (code at https://sr.ht/~alexwennerberg/flounder/)

Wasn't sure what section to put it in, it's a hosted shared gemini platform, similar to geocities/neocities but for gemini

**Comment by kr1sp1n** [comment]
@alexwennerberg Thanks for the hint. I even was already a member of this great service. I just added it to the "Services" section: https://github.com/kr1sp1n/awesome-gemini#services
