### ISSUE TITLE
List guidelines not found

### ISSUE THREAD

**Issue by bortzmeyer** [kr1sp1n/awesome-gemini#34]
https://github.com/kr1sp1n/awesome-gemini/blob/master/contributing.md says "Please ensure your pull request adheres to the list guidelines." but "list guidelines" is a link to a non-existing page.

**Comment by kr1sp1n** [comment]
@bortzmeyer I copied the `contributing.md` from [here](https://github.com/sindresorhus/awesome). I think the list guidelines are [here](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). But to be honest I don't care about these guidelines. Too much overhead. So I think I will remove or simplify the `contributing.md`. Thanks for the hint 🙏
