### ISSUE TITLE
Gemini iOS

### ISSUE THREAD

**Issue by scott-joe** [kr1sp1n/awesome-gemini#4]
https://github.com/pitr/gemini-ios You can install with via Test Flight. It's the same guy as `gig`

**Comment by kr1sp1n** [comment]
@scott-joe I really appreciate your contributions but would you mind to open a PR instead of an issue? So I could review your PR and just merge it. So we can share the effort. A little effort for you and a little effort for me. Thanks 🙏 If you need help with opening a PR I am glad to help you.

**Comment by ivan-avalos** [comment]
Oh, I didn't know there was a TestFlight! I gotta try right now.

**Comment by ivan-avalos** [comment]
The TestFlight link is broken, btw.

**Comment by pitr** [comment]
I’ll take a look today

**Comment by pitr** [comment]
TestFlight link seems to work for me - https://testflight.apple.com/join/ln6yTtqK

There is a link to AppStore in the repo but since it hasn’t been added to the AppStore it doesn’t work. I’ll replace it with TestFlight link

**Comment by scott-joe** [comment]
@kr1sp1n Sure thing. I was doing it from my phone, so I'll just make a note for myself to make a PR instead.

**Comment by kr1sp1n** [comment]
@scott-joe Thanks 😊  If you use an iOS device I can recommend "Working Copy" as a git client to edit repos while you are on the road: https://workingcopyapp.com/
