### ISSUE TITLE
Mark Moonlander as abandoned?

### ISSUE THREAD

**Issue by kwadroke** [kr1sp1n/awesome-gemini#54]
Per the Moonlander Git Repo https://sr.ht/~admicos/moonlander/, the project isn't maintained any more.
> Moonlander has been abandoned for a few months at this point, and will likely not be maintained on it's current form. 

Perhaps mark it as such, instead of removing it.

**Comment by Admicos** [comment]
Hey, Moonlander dev here.

Over the last week or so I've been rewriting Moonlander, and it's no longer abandoned, though it is _incomplete_, which might need to be tagged differently depending on how y'all do stuff here.

**Comment by kwadroke** [comment]
Closing this then. When I created isse this the repo was marked abandoned.
Good to see it continue.
