### ISSUE TITLE
clarify or remove graphical client "spacewar"

### ISSUE THREAD

**Issue by binyamin** [kr1sp1n/awesome-gemini#96]
According to [spacewar's readme](https://github.com/ResonAtom/spacewar#readme), this graphical client "mostly doesn't work". First, it's a bit odd to include a half-made project with tested GUIs like Castor and Lagrange. It feels misleading. Second, awesome-lists tend to curate _the best projects_ out there.

**Ideas**
1. Remove this entry
2. Clarify that this project is an example project, and not a full-blown solution
3. Move it to a subsection specifically examples, samples, works-in-progress, etc.

See 102f103cc8fb1567d0814a8b8892f4108ed01aca

**Comment by kr1sp1n** [comment]
@binyamin Thanks for your hints.
I clarified that the spacewar client is experimental and unstable.
But I think that even those entries are important for the list and the gemini community.
Someone could learn from the code or improve it even further. So my goal is to collect as many code repos and software, even if they are not fully functional. But I will try to mark those along the growth of the list.
Thanks! 😊

**Comment by binyamin** [comment]
@kr1sp1n That makes a lot of sense. I had actually been building one myself, called Gemium (https://github.com/gemium/gemium). It's a WIP. I don't want to open a PR because it's my own project. Feel free to add it.
